#!/usr/bin/env bash
#
# generate-sbom.sh — regenerate the repo-root CycloneDX SBOM via Syft.
#
# Why Syft (anchore/syft):
# - Apache 2.0, single Go binary, sigstore-signed releases.
# - First-class CycloneDX + SPDX support.
# - Aligns with the project's internal SBOM strategy.
#
# Why this lives in scripts/ rather than the Dockerfile:
# - The SBOM is part of the SOURCE artifact, not the runtime image. The
#   committed sbom.cdx.json is what we ship/scan against; the image SBOM
#   is regenerated by CI from the same source and should match.
# - Developers regenerate locally before pushing; CI verifies the committed
#   SBOM is not stale.
#
# Defensive choices:
# - `set -euo pipefail` so a partial SBOM is never written.
# - Fail loud (not silent) if Syft is missing — never proceed without an
#   SBOM. The point of this script is to PRODUCE one.
# - Scan the source directory, not an image — works without docker on the
#   developer host.
# - Output is checked-in (sbom.cdx.json), so pin formatter behaviour:
#   `--output cyclonedx-json=sbom.cdx.json` (no pretty-print drift between
#   developers).
#
# Usage:
#   scripts/generate-sbom.sh                  # writes ./sbom.cdx.json
#   scripts/generate-sbom.sh --check          # diffs against repo head, fails on drift (CI use)
#
# Exit codes:
#   0  SBOM written / matches HEAD
#   1  Syft missing or invocation failed
#   2  Drift detected (--check mode only)

set -euo pipefail
IFS=$'\n\t'

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$REPO_ROOT/sbom.cdx.json"
CHECK_MODE=0

for arg in "$@"; do
  case "$arg" in
    --check) CHECK_MODE=1 ;;
    -h|--help) sed -n '2,40p' "$0"; exit 0 ;;
    *) echo "unknown flag: $arg" >&2; exit 1 ;;
  esac
done

if ! command -v syft >/dev/null 2>&1; then
  echo "[error] syft not on PATH. Install via:" >&2
  echo "         https://github.com/anchore/syft#installation" >&2
  echo "         (verify the cosign signature on the release before installing)" >&2
  exit 1
fi

# Source-directory scan. We deliberately do not scan an image here because
# (a) we don't always have docker on the dev host, and (b) the runtime
# image's SBOM is generated by CI as a release artifact and should be
# identical to this once base-image packages are folded in.
TMP="$(mktemp -t sbom.XXXXXX.json)"
trap 'rm -f "$TMP"' EXIT

cd "$REPO_ROOT"

# Single source of truth for the version: VERSION file at repo root.
# Falls back to "dev" so an SBOM can still be produced on a working tree
# that doesn't carry a VERSION file (early-stage repos).
VERSION="$(cat "$REPO_ROOT/VERSION" 2>/dev/null | tr -d '[:space:]' || true)"
VERSION="${VERSION:-dev}"

# Exclude development-only tree pollution that Syft would otherwise pick
# up as "components" the project depends on:
#   .venv-*           — local dev/smoke venvs (dev artefact, not source)
#   .git              — VCS metadata
#   SSC/raw           — scanner raw outputs (large + ephemeral)
#   __pycache__       — bytecode caches
#   node_modules      — leftover from the Node prototype era
syft "dir:." \
  --exclude './.venv-*/**' \
  --exclude './.git/**' \
  --exclude './SSC/raw/**' \
  --exclude './**/__pycache__/**' \
  --exclude './node_modules/**' \
  --output "cyclonedx-json=$TMP" \
  --source-name genesis-shim \
  --source-version "$VERSION" \
  --quiet

if [ "$CHECK_MODE" -eq 1 ]; then
  if ! diff -q "$TMP" "$OUT" >/dev/null 2>&1; then
    echo "[drift] committed sbom.cdx.json does not match what Syft would produce." >&2
    echo "       run scripts/generate-sbom.sh and commit the result." >&2
    exit 2
  fi
  echo "[ok] sbom.cdx.json matches current source"
else
  cp "$TMP" "$OUT"
  echo "[ok] wrote $OUT"
fi
